service: python-dynamodb
provider:
  name: aws
  runtime: python3.8
  environment: ${file(env.yml)}

functions:
  crearTabla:
    handler: api/crearTabla.handler
  eliminarTabla:
    handler: api/eliminarTabla.handler
  insertarRegistro:
    handler: api/insertarRegistros.handler
  eliminarRegistro:
    handler: api/eliminarRegistro.handler
  actualizarRegistro:
    handler: api/actualizarRegistro.handler
  scanRegistros:
    handler: api/scanRegistros.handler
  queryRegistros:
    handler: api/queryRegistros.handler